### ISSUE TITLE
服务器中使用低压蒸汽合金炉会导致服务器崩溃

### ISSUE THREAD

**Issue by HUCSr** [ProgregssTeam/GregFactory-Sky#30]
```cpp
[026月2024 23:45:54.046] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
[026月2024 23:45:54.047] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at com.lowdragmc.lowdraglib.emi.EMIPlugin.isEmiEnabled(EMIPlugin.java:32) ~[ldlib-forge-1.20.1-1.0.25.d.jar%23257!/:?]
	at com.lowdragmc.lowdraglib.LDLib.isEmiLoaded(LDLib.java:81) ~[ldlib-forge-1.20.1-1.0.25.d.jar%23257!/:?]
	at com.lowdragmc.lowdraglib.LDLib.isJeiLoaded(LDLib.java:73) ~[ldlib-forge-1.20.1-1.0.25.d.jar%23257!/:?]
	at com.gregtechceu.gtceu.api.recipe.ui.GTRecipeTypeUI.lambda$createEditableUITemplate$8(GTRecipeTypeUI.java:222) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.gui.editor.IEditableUI$Normal.setupUI(IEditableUI.java:28) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.recipe.ui.GTRecipeTypeUI.createUITemplate(GTRecipeTypeUI.java:162) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.machine.steam.SimpleSteamMachine.createUI(SimpleSteamMachine.java:160) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.gui.factory.MachineUIFactory.createUITemplate(MachineUIFactory.java:31) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.gui.factory.MachineUIFactory.createUITemplate(MachineUIFactory.java:21) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.lowdragmc.lowdraglib.gui.factory.UIFactory.openUI(UIFactory.java:39) ~[ldlib-forge-1.20.1-1.0.25.d.jar%23257!/:?]
	at com.gregtechceu.gtceu.api.machine.feature.IUIMachine.tryToOpenUI(IUIMachine.java:26) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at com.gregtechceu.gtceu.api.block.MetaMachineBlock.m_6227_(MetaMachineBlock.java:289) ~[gtceu-1.20.1-1.2.0.a-build_594.jar%23202!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23233!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.platform.EmiAgnos.isForgeAgnos()" because "dev.emi.emi.platform.EmiAgnos.delegate" is null
	at dev.emi.emi.platform.EmiAgnos.isForge(EmiAgnos.java:34) ~[emi-1.1.4+1.20.1+forge.jar%23182!/:?]
	at dev.emi.emi.config.EmiConfig.<clinit>(EmiConfig.java:105) ~[emi-1.1.4+1.20.1+forge.jar%23182!/:?]
	... 31 more
[026月2024 23:45:54.228] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@298b64f7
[026月2024 23:45:54.228] [Server thread/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@6e8cf4c6
[026月2024 23:45:54.441] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7b23bf3d-3f4c-4437-bb0e-d378639f8c39
[026月2024 23:45:54.446] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: D:\Download\GregFactory Sky-1.0.3-ServerPack\GregFactory Sky-1.0.3-ServerPack\.\crash-reports\crash-2024-06-02_23.45.54-server.txt
[026月2024 23:45:54.448] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[026月2024 23:45:54.452] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[026月2024 23:45:54.491] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[026月2024 23:45:55.019] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[026月2024 23:45:55.508] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[026月2024 23:45:55.513] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[026月2024 23:45:55.518] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
[026月2024 23:45:55.523] [Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: Gathering id map for writing to world save world
[026月2024 23:45:55.560] [Server thread/DEBUG] [net.minecraftforge.common.ForgeHooks/WP]: ID Map collection complete world
[026月2024 23:45:55.616] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[026月2024 23:45:55.616] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[026月2024 23:45:55.618] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[026月2024 23:45:55.621] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[026月2024 23:45:55.621] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[026月2024 23:45:55.640] [Server thread/INFO] [FTB Chunks/]: Shutting down map thread
[026月2024 23:45:55.640] [Server thread/DEBUG] [net.minecraftforge.fml.config.ConfigTracker/CONFIG]: Unloading configs type SERVER
[026月2024 23:46:14.161] [ftbbackups2_QuartzSchedulerThread/DEBUG] [net.creeperhost.ftbbackups.repack.org.quartz.core.QuartzSchedulerThread/]: batch acquisition of 0 triggers
[026月2024 23:46:43.174] [ftbbackups2_QuartzSchedulerThread/DEBUG] [net.creeperhost.ftbbackups.repack.org.quartz.core.QuartzSchedulerThread/]: batch acquisition of 0 triggers
[026月2024 23:46:55.018] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[026月2024 23:46:55.018] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[026月2024 23:46:55.485] [Server Watchdog/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@298b64f7
[026月2024 23:46:55.485] [Server Watchdog/DEBUG] [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@6e8cf4c6
[026月2024 23:46:55.557] [Server Watchdog/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8f660ad8-196f-49f8-abdc-b62e7debcf04
[026月2024 23:46:55.591] [Server Watchdog/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 65ac45c7-ad8c-46d5-9438-b1c27014cf53
[026月2024 23:46:55.593] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/]: This crash report has been saved to: D:\Download\GregFactory Sky-1.0.3-ServerPack\GregFactory Sky-1.0.3-ServerPack\.\crash-reports\crash-2024-06-02_23.46.55-server.txt
```
正常单人游玩似乎没有问题

**Comment by nath08523** [comment]
我也有遇到這個問題，下載LDLib 1.20.1-1.0.25.r-forge後，就可正常開啟低壓蒸汽合金爐了。
但是只能運作一次，
我是用銅粉+紅石粉=紅色合金錠的配方，各放一組只能出一個紅色合金錠，後續不會繼續運作，
拆掉重裝一樣只會運作一次。

**Comment by CJZZX** [comment]
删了服务端mods里的EMI
